defmodule RailwayAppWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :railway_app

  # Caches the raw request body for HMAC signature verification.
  # Only caches when the body fits in a single read (safe for webhook payloads).
  def read_body_cache(conn, opts) do
    case Plug.Conn.read_body(conn, opts) do
      {:ok, body, conn} ->
        {:ok, body, Plug.Conn.put_private(conn, :raw_body, body)}

      other ->
        other
    end
  end

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_railway_app_key",
    signing_salt: "m0LtV3eC",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # Serve favicon files separately to handle digested filenames (favicon-*.ico)
  plug Plug.Static,
    at: "/",
    from: :railway_app,
    gzip: not code_reloading?,
    only_matching: ~w(favicon)

  plug Plug.Static,
    at: "/",
    from: :railway_app,
    gzip: not code_reloading?,
    only: RailwayAppWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :railway_app
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {__MODULE__, :read_body_cache, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RailwayAppWeb.Router
end
